### ISSUE TITLE
`getClrVersionString()` fails after enabling rDotNet

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rClr#30]
In `loadAndInit()`:

```
getClrVersionString()
invisible(clrCallStatic("Rclr.RDotNetDataConverter", "SetRDotNet", TRUE))
```

works, but 

```
invisible(clrCallStatic("Rclr.RDotNetDataConverter", "SetRDotNet", TRUE))
getClrVersionString()
```

fails with 

```
Error: 'getCurrentConvertedObject' is not an exported object from 'namespace:rClr'
Error in clrCallStatic(clrFacadeTypeName, "GetFieldOrProperty", objOrType,  : 
  Type:    RDotNet.EvaluationException
Message: Error: 'getCurrentConvertedObject' is not an exported object from 'namespace:rClr'

Method:  RDotNet.SymbolicExpression Parse(System.String, System.Text.StringBuilder, RDotNet.REnvironment)
Stack trace:
   at RDotNet.REngine.Parse(String statement, StringBuilder incompleteStatement, REnvironment environment)
   at RDotNet.REngine.<Defer>d__63.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at RDotNet.REngine.Evaluate(String statement, REnvironment environment)
   at Rclr.RDotNetDataConverter.get_CreateClrS4Object()
   at Rclr.RDotNetDataConverter.CreateClrObj(Object obj)
   at Rclr.RDotNetDataConverter.ConvertObject(Object obj)
   at Rclr.RDotNetDataConverter.TryConvertToSexp(Object obj)
   at Rclr.RDotNetDataConverter.ConvertToR(Object obj)
   at Rclr.ClrFacade.marshallDataToR(Object obj, Boolean tryUseConverter)
   at Rclr.ClrFacade.invokeMethod(Object obj, Object[] arguments, MethodInfo me
```

Have to investigate why.

**Comment by PavelBal** [comment]
Function is not used any more.
